CREATE TABLE skills (name TEXT,
                     ability TEXT,
                     barbarian INTEGER,
                     bard INTEGER,
                     cleric INTEGER,
                     druid INTEGER,
                     fighter INTEGER,
                     monk INTEGER,
                     paladin INTEGER,
                     ranger INTEGER,
                     rogue INTEGER,
                     sorcerer INTEGER,
                     wizard INTEGER,
                     untrained INTEGER,
                     armorcheck INTEGER);
